# Generated by Django 6.0.7 on 2026-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('Course', 'Course'), ('Internship', 'Internship')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=150)),
                ('learning_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Offline', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission / Internship',
                'verbose_name_plural': 'Admissions & Internships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('Service', 'Service'), ('Project', 'Project'), ('Contact', 'Contact'), ('FAQ', 'FAQ')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'General Enquiry',
                'verbose_name_plural': 'General Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
