# Generated by Django 6.0.7 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genixapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('college', models.CharField(blank=True, max_length=150, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=150, null=True)),
                ('learning_mode', models.CharField(default='Hybrid', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Enquiry',
                'verbose_name_plural': 'Course Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='course',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('Course', 'Course'), ('Internship', 'Internship')], default='Course', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='learning_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Hybrid', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
